[workspace]
authors = ["Davoody, Amirhossein <amirhossein.davoody@gmail.com>"]
channels = ["conda-forge"]
name = "spice_result_parser"
platforms = ["linux-64"]
preview = ["pixi-build"]
version = "0.1.0"

[system-requirements]
libc = {family = "glibc", version = "2.22"}
linux = "4.12.14"

[tasks]
release = {cmd = "./release.sh", description = "Release the package", cwd = "."}
test = {cmd = 'python -m unittest discover -s test -p "test_*.py"', description = "Run unit tests"}

[dependencies]
spice_result_parser = {path = "."}
numpy = ">=2.3.4,<3"
python = ">=3.9"

[package]
description = "A low-memory parser for HSPICE and Nutmeg (ngspice/SPICE3) simulation result files, with an MCP server for agents."
name = "spice_result_parser"
version = "0.1.0"

[package.build]
backend = {name = "pixi-build-python", version = "==0.4.0"}

[package.host-dependencies]
hatchling = ">=1.26.3"

[package.run-dependencies]
numpy = "*"
python = ">=3.9"
